#:schema node_modules/wrangler/config-schema.json
name = "sublink-yunyuhai"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "20799120d4bc4aab9131651e4ad8a7a9" }
]

[assets]
directory = "./public"
